### PR TITLE
Utilize uniqueKey for exec, fix measure bug

### LINKED ISSUE #62: JS error on package when linting multiple open files concurrently
Steps to reproduce (preferable to be developing this package to see the codeclimate commands executed in the console):

1. Open multiple files to be linted (I open one css and one yaml, for example).
1. Close Atom.
1. Re-open Atom with `atom -d`to keep your previous context (the files of step 1 should be opened again).
1. Open dev tools and check the console. You should something like this:

```javascript
linter-registry.js [sm]:144 [Linter] Error running Code Climate DOMException: Failed to execute 'measure' on 'Performance': The mark 'linter-codeclimate: Analysis-start' does not exist.
    at Error (native)
    at endMeasure (/opt/cgalvarez/linter-codeclimate/lib/index.js:34:17)
    at Object.<anonymous> (/opt/cgalvarez/linter-codeclimate/lib/index.js:244:9)
    at next (<anonymous>)
    at step (/opt/cgalvarez/linter-codeclimate/lib/index.js:7:273)(anonymous function) @ linter-registry.js [sm]:144
```

Because of long execution times of codeclimate (that's the reason behind PR #61), this should fail quite often (the affected code is not enclosed inside an `if (atom.inDevMode()) {` block, so it is run on every lint).

Running the affected code only in dev mode will still fire the error (although only in dev mode).

Besides, the message itself is not very detailed: `linter-codeclimate: Analysis took:  6739.615000000001`, so I think the easiest and most simple solution woud be using a string customized for the linted file, logging something like `linter-codeclimate: Analysis for style.css took:  6739.615000000001`.

### PR DESCRIPTION
**Pull request by cgalvarez**
This PR fixes next issues:

- Multiple CodeClimate executions for the same source file (through the option `uniqueKey`): now there is only one execution running for a given source file (which improves performance and saves device resources). For heavy executions, 
- Set performance marks based upon the source file's relative path, which allows measuring correctly the concurrent linting of different source files.

Fixes #62.

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -202,6 +207,7 @@ export default {
           [relpath, '</dev/null']);
         const execOpts = {
           cwd: dirname(configurationFilePath),
+          uniqueKey: relpath,
```
Comment (Arcanemagus) [inline lib/index.js]: I hadn't even thought about this needing to be file specific in the other `uniqueKey` PR, good call!

However, this doesn't take into account there being more than one provider running at a time for the same file. The instances of `atom-linter` _should_ be isolated from each other, but we might as well tag this with the provider name, something like `` `linter-codeclimate::${relpath}` ``.

File: lib/index.js [hunk 2]
```diff
@@ -24,7 +24,12 @@ const getEnabledEngines = (configFilePath) => {
 const badCommands = new Set();
 
 const startMeasure = (baseName) => {
-  performance.mark(`${baseName}-start`);
+  const startMark = `${baseName}-start`;
+  // clear start mark from previous execution for the same file
```
Comment (Arcanemagus) [inline lib/index.js]: "clear" -> "Clear"

Comment (Arcanemagus) [reply lib/index.js]: Good call btw, I think that fixes an odd bug I ran into rarely while testing this.

File: lib/index.js [hunk 3]
```diff
@@ -226,6 +233,12 @@ export default {
           notifyError(e, `${this.executablePath} ${execArgs.join(' ')}`);
           return null;
         }
+
+        // handle unique spawning: killed execs will return null
```
Comment (Arcanemagus) [inline lib/index.js]: "handle" -> "Handle"

File: lib/index.js [hunk 4]
```diff
@@ -226,6 +233,12 @@ export default {
...
+        if (result === null) {
+          return [];
```
Comment (Arcanemagus) [inline lib/index.js]: Return `null` here, telling Linter not to update any messages it currently has saved for the provider. (`[]` tells it there are _no_ messages, so it will wipe the slate clean!)

**Review by Arcanemagus — CHANGES_REQUESTED** [review]

**Comment by cgalvarez** [comment]
@Arcanemagus glad to help with those odd bugs that drive us crazy!! :stuck_out_tongue_winking_eye: All your requested changes are commited, sir.

**Review by Arcanemagus — APPROVED** [review]

**Comment by Arcanemagus** [comment]
Glad to see somebody taking an interest in fixing things up, I'd be perfectly fine with giving you write access to this repo if @AtomLinter/linter-codeclimate has no issues with it and you were interested.

**Comment by cgalvarez** [comment]
Of course! I'm actively using this package right now, so I can assure you any bug that I found or any enhancement that I can think of, I will PR it.

**Comment by Arcanemagus** [comment]
As I'm implementing this myself in something now, I just thought of something:

Can you think of a reason to keep around the execution timeout with the `uniqueKey` being implemented? It should be handling killing older runs for us now so the timeout should just be set to `Infinity` permanently and the option removed as far as I can see.

**Comment by cgalvarez** [comment]
The unique reason I can think of is that if an exec just hangs up and keeps running indefinitely in the background, it will only be killed by one of two:

1. The timeout (which we are debating to kill).
1. Resaving the file which produced the soooo long execution.

But if either the file itself or the command itself is the problem, it could be running indefinitely without the timeout.

Take into account that `uniqueKey` only kills long-time commands if **you re-save** the file that executed it.

That's why I initially proposed to set it as an integer, because you can set a numeric timeout that you understand as high enough to be killed. If user provides a timeout of 0, then it´s set to `Infinity`.

I *personally* have set it up to `Infinity` right now, because I´m testing the package thoroughly to fix any bugs I found, but you should consider that in the package you are implementing this.

**Comment by Arcanemagus** [comment]
Yea, if a process really is running forever though, it will eventually get killed when Atom exits (supposing that it will even die in the first place).
