### PR TITLE
Fix/one spawn per project

### LINKED ISSUE #69: Run only on changed code
Hi,
Is there a way to have the code climate linter run only on changed code (similar to the way it runs on the web app) rather than analyzing the whole file?

### LINKED ISSUE #75: `codeclimate init` is not a valid command
I am running codeclimate v0.70.3 and the only commands available are [these](https://github.com/codeclimate/codeclimate#commands)

The files no longer get linted, even though I have docker installed and a valid `.codeclimate.json` file. The command `codeclimate analyze -f json app/controllers/index.js` runs properly on the command line and produces the json, but doesn't seem to work in Atom

### LINKED ISSUE #76: CodeClimate JSON Formatter Update Causing Getting Error [Linter] Error running Code Climate TypeError: Cannot convert undefined or null to object
I'm using CodeClimate version 0.70.3

When running the linter on a ruby file, I got this error on the console 
`[Linter] Error running Code Climate TypeError: Cannot convert undefined or null to object`

After some investigation, the root cause was this [line](https://github.com/AtomLinter/linter-codeclimate/blob/master/lib/index.js#L231) in `index.js` file.
It's trying to access `issue.location`, but the issue object has no `location` key.

That's the output of running `codeclimate -f json /path/to/file.rb`
```json
[
  {
    "name":"ruby.parse.succeeded",
    "type":"measurement",
    "value":1,
    "engine_name":"structure"
  },
  {
    "type":"Issue",
    "check_name":"sql_injection",
    "description":"Possible SQL injection",
    "fingerprint":"...",
    "categories":[
      "Security"
    ],
    "severity":"minor",
    "remediation_points":300000,
    "location":{
      "path":"/path/to/file.rb",
      "lines":{
        "begin":23,
        "end":23
      }
    },
    "content":{
      "body":"..."
    },
    "engine_name":"brakeman"
  },
  {
    "type":"Issue",
    "check_name":"Rubocop/Metrics/CyclomaticComplexity",
    "description":"Cyclomatic complexity for load_resources is too high. [8/6]",
    "categories":[
      "Complexity"
    ],
    "remediation_points":1140000,
    "location":{
      "path":"/path/to/file.rb",
      "positions":{
        "begin":{
          "column":3,
          "line":107
        },
        "end":{
          "column":6,
          "line":114
        }
      }
    },
    "content":{
      "body":"..."
    },
    "fingerprint":"...",
    "engine_name":"rubocop",
    "severity":"minor"
  }
]
```
You can notice that the first element in the output is of type `measurments` not `Issue`, this has been [recently introduced](https://github.com/codeclimate/codeclimate/commit/c1d68026941178d8eb89e81bcad3aa65e6b4e6ed) in codeclimate json formatter.

So as a quick solution, I just added this condition inside the `forEach` block
```javascript
if (issue.type !== 'Issue') {
  return;
}
```
We may also filter the `messages` before calling `forEach`.

Do you have a specific guide to create a pull request with this fix?

### LINKED ISSUE #81: Running cli twice on save, improve performance
Right now the cli is being run twice on each file save.

You can check your open processes with `ps aux | grep 'codeclimate analyze'` or by taking a look at the Atom's dev console (`ctrl + alt + i`) messages.

I think the approach is just plain wrong. Right now, the command executed is `codeclimate analyze -f json path/to/changed/file`, and as such, only analyzes the changed file. We're missing some useful and invaluable issues reported by CodeClimate, as duplicated code detection (since this can affect more than one file).

Each time a new save takes place, a new cli executions is spawned. I think it would be preferable to spawn only one cli execution per project (if any of its files is changed), and drop issues of closed files (to avoid errors when [calculating range from the textEditor](https://github.com/AtomLinter/linter-codeclimate/blob/master/lib/index.js#L255)).

With this approach, I think keeping a dictionary with each project root and its associated promise (of its spawned cli execution) would allow to kill the ongoing analysis and start the new one on consecutive savings, without having multiple parallel executions in the background per project.

Also, it would be desirable to *debounce* the execution, so we could avoid the double current execution (I have no idea of which is causing it).

### PR DESCRIPTION
**Pull request by cgalvarez**
This PR has the following goals:

- [x] Massive refactor of the code.
- [x] Analyze the whole project, not only the currently open file, so allowing for any engine and including previously missing issues like *duplicated code*.
- [x] Debounce the linting process, so multiple files from the same project can merge into one unique analysis.
- [x] Remove some code that doesn't make sense or it's outdated.
- [x] [Fix](https://codeclimate.com/github/AtomLinter/linter-codeclimate/pull/83) all currently [reported issues on CodeClimate](https://codeclimate.com/github/AtomLinter/linter-codeclimate). I've managed to comply with the cognitive complexity. Hope @Arcanemagus likes the final refactor :wink: 
- [x] Proper docblocks for each function.

And still waiting for the following bugs to be fixed in their respective repos:

- [`phpmd/phpmd`: duplicated issues](https://github.com/phpmd/phpmd/issues/467)
- [`steelbrain/exec`: bug when `exitCode` is `null`](https://github.com/steelbrain/exec/issues/97)

There are some issues left that are very annoying, but I don't have any clue on how to fix them, and can be the subject of future PRs:

- On the first Atom run (right after opening Atom for the first time or reloading it with `control + shift + F5`), the CLI is ran multiple times (typically two). The debounced linting cannot address this issue because the time between the executions exceeds 2s, and setting the debounce timeout to that feels overkilling, and make the whole point of this PR useless.
- When starting Atom with multiple files open, changing from one to another still triggers a new analysis. This could be addressed to improve performance.
- When starting Atom with multiple files open, the CodeClimate issues are generated correctly for AtomLinter, but they never get added. User need to manually re-trigger analysis by saving a file to get the issues included in AtomLinter pane.

Also, this PR...

Fixes #75
Fixes #76
Closes #77 with a temporary workaround
Fixes #81 
Closes #69, since it should be supported by CodeClimate CLI in first place, and it should miss some issues (like *duplicated code*), which this PR aims to solve.
Closes #74 
Closes #77
Closes #78

_Edited by @Arcanemagus to automatically close issues/PRs._

### CODE REVIEW

**Comment by cgalvarez** [comment]
The tests seem to hang, cannot make them even print any error.

Anyone that could lend me a hand on this? This PR can be installed and tested locally with:

```shell
git clone -b 'fix/one-spawn-per-project' https://github.com/cgalvarez/linter-codeclimate.git linter-codeclimate-pr
cd ./linter-codeclimate-pr
apm link --dev
apm install
atom -d .
```

**Comment by cgalvarez** [comment]
Wow, I was about to give up, but the tests take ~273s on CI to finish!! Locally ~20s. What an amazing difference... but finally get it working and passing!! :tada: :tada: :tada:

**Comment by EugeneGrigorenko** [comment]
Is it gonna be merged?

**Comment by Arcanemagus** [comment]
Looks like the Code Climate people aren't maintaining this 😆😢.

Taking a look over this now, that diff summary looks daunting 😮.

File: lib/index.js [hunk 1]
```diff
@@ -1,88 +1,356 @@
 'use babel';
 
+/* eslint no-use-before-define:0 */
```
Comment (Arcanemagus) [inline lib/index.js]: Is disabling this _absolutely_ necessary? If so, this should be moved to the general ESLint configuration.

File: lib/index.js [hunk 2]
```diff
@@ -120,163 +384,14 @@ export default {
   },
 
   provideLinter() {
-    const Helpers = require('atom-linter');
-    const configurationFile = '.codeclimate.yml';
     return {
       name: 'Code Climate',
       grammarScopes: ['*'],
       scope: 'file',
```
Comment (Arcanemagus) [inline lib/index.js]: The readme section saying this only worked for single file analysis has been removed... which implies that results for _any_ file can be returned. If that's the case this should be changed to `project`.

File: lib/index.js [hunk 3]
```diff
@@ -1,88 +1,356 @@
...
+ * @return  {Promise}               An object with the absolute paths to project/triggering file.
+ */
+const track = async (textEditor) => {
+  const path = { file: textEditor.getPath() };
+
+  // Exit early on `untitled` files (not saved into disk yet)
+  if (path.file === undefined) return path;
+
+  // Fetch previously cached paths when available.
+  if (ccLinter.openOnTextEditor[path.file]) {
```
Comment (Arcanemagus) [inline lib/index.js]: This is accessing properties of the package object, just make this a method of that object.

File: lib/index.js [hunk 4]
```diff
@@ -1,88 +1,356 @@
...
+ * @todo    Remove option `ignoreExitCode` after fixing https://github.com/steelbrain/exec/issues/97
+ */
+const runCli = async (cwd) => {
+  const execOpts = {
+    cwd,
+    uniqueKey: cwd,
+    ignoreExitCode: true,
+  };
+
+  if (ccLinter.disableTimeout || global.waitsForPromise) {
```
Comment (Arcanemagus) [inline lib/index.js]: This is accessing properties of the package object, just make this a method of that object.

File: lib/index.js [hunk 5]
```diff
@@ -1,88 +1,356 @@
...
+/**
+ * @summary Runs the CodeClimate CLI in a spawned process.
+ * @param   {String}        cwd The absolute path to the project root.
+ * @return  {Promise|null}      Promise with the output from executing the CLI.
+ * @todo    Remove option `ignoreExitCode` after fixing https://github.com/steelbrain/exec/issues/97
+ */
+const runCli = async (cwd) => {
+  const execOpts = {
+    cwd,
+    uniqueKey: cwd,
```
Comment (Arcanemagus) [inline lib/index.js]: This should have the provider name added in case the user has multiple providers running on the same directory.

File: lib/index.js (hunk 4 above)
Comment (Arcanemagus) [reply lib/index.js]: `global.waitsForPromise` should be replaced with `atom.inSpecMode()`.

File: lib/index.js [hunk 6]
```diff
@@ -1,88 +1,356 @@
...
 
-const startMeasure = (baseName) => {
-  const startMark = `${baseName}-start`;
-  // Clear start mark from previous execution for the same file
-  if (performance.getEntriesByName(startMark).length) {
-    performance.clearMarks(startMark);
-  }
-  performance.mark(startMark);
+const configurationFile = '.codeclimate.yml';
+const execArgs = ['analyze', '-f', 'json'];
```
Comment (Arcanemagus) [inline lib/index.js]: There is no reason to have this here, move it down to `runCli`.

File: lib/index.js [hunk 7]
```diff
@@ -1,88 +1,356 @@
...
+const logHeader = 'linter-codeclimate::';
+const linting = {};
+const fingerprints = {};
+const debounceTimeout = 250;
+const mapSeverity = {
+  major: 'error',
+  minor: 'warning',
+};
+const notificationDefaults = {
```
Comment (Arcanemagus) [inline lib/index.js]: Define this where it is used, there is no reason to declare it file scoped.

File: lib/index.js [hunk 8]
```diff
@@ -1,88 +1,356 @@
...
+  buttons: [{
```
Comment (Arcanemagus) [inline lib/index.js]: Why does _every single_ notification need this button?

File: lib/index.js [hunk 9]
```diff
@@ -1,88 +1,356 @@
...
+    className: 'btn-install',
+    onDidClick: () => {
+      // eslint-disable-next-line import/no-extraneous-dependencies
+      require('shell').openExternal('https://github.com/codeclimate/codeclimate');
+    },
+    text: 'Install guide',
+  }],
+  dismissable: true,
```
Comment (Arcanemagus) [inline lib/index.js]: Just a note, `dismissable` is rather badly named. It actually means the user _must_ dismiss the notification manually. This may or may not be what you intended.

If omitted or set to `false` it will disappear automatically after the standard delay.

File: lib/index.js [hunk 10]
```diff
@@ -1,88 +1,356 @@
...
+  return linterResults;
 };
 
-export default {
+/**
+ * @summary Debounces the linting to join triggerings from multiple files of same project.
+ * @param   {TextEditor} textEditor The TextEditor instance of the triggering file.
+ * @return  {Promise}               An array of issues in the format that AtomLinter expects.
+ */
+const debouncedLint = async (textEditor) => {
```
Comment (Arcanemagus) [inline lib/index.js]: `linter` already debounces calls to `lint` with a user configurable delay. Is this necessary to duplicate the work here?

File: lib/index.js (hunk 3 above)
Comment (Arcanemagus) [reply lib/index.js]: Actually, `ccLinter.openOnTextEditor` is _never_ populated, so this can be simplified to `if (false)`, I'm guessing that's not what you intended?

File: lib/index.js [hunk 11]
```diff
@@ -1,88 +1,356 @@
...
+ */
+const parseIssues = (path, result) => {
+  let messages;
+
+  try {
+    messages = JSON.parse(result);
+  } catch (e) {
+    notifyError(e, 'Invalid JSON returned from CodeClimate. See the Console for details.');
+    // eslint-disable-next-line no-console
+    console.error('Invalid JSON returned from CodeClimate:', result);
```
Comment (Arcanemagus) [inline lib/index.js]: Why not just `console.error` inside `notifyError`?

File: lib/index.js [hunk 12]
```diff
@@ -1,88 +1,356 @@
...
+
+/**
+ * @summary Fetch the paths of all currently open files on Atom.
+ * @return  {Object} Dictionary of open file abspaths ~> textEditor.
+ *
+ * NOTE Files indexed by abspath to avoid relative filepath collision among different projects.
+ */
+const fetchOpenFilepaths = () => {
+  const openFiles = {};
+  atom.workspace.textEditorRegistry.editors.forEach((textEditor) => {
```
Comment (Arcanemagus) [inline lib/index.js]: `atom.workspace.textEditorRegistry.editors` is a private property, this should be `atom.workspace.getTextEditors()`.

Also instead of calling this every single time, it might be better to do `atom.workspace.observeTextEditors()`.

File: lib/index.js [hunk 13]
```diff
@@ -1,88 +1,356 @@
...
+
+  const open = fetchOpenFilepaths();
+  const linterResults = [];
+  messages.forEach((issue) => {
+    // Exit early if not an issue
+    if (issue.type.toLowerCase() !== 'issue') return;
+
+    // Exit early if issued file is not open
+    const file = join(path.project, issue.location.path);
+    if (!open[file]) return;
```
Comment (Arcanemagus) [inline lib/index.js]: I would instead use something like [findTextEditor](https://github.com/AtomLinter/linter-elixirc/blob/987d21dca55131fa061223a0d80b138c30f7d4a1/lib/init.js#L104-L111) to get the `TextEditor` for a file _if one is available_, if not return the best position you can. If the user then opens the file a `TextEditor` will be available and a more accurate position can be determined from that.

Once you start returning results for anything other than the active `TextEditor` that you are passed, you _must_ change the scope to `project`, and since that allows you to send results for _any_ path, there is no reason to only filter results to ones that the user has open.

File: lib/index.js [hunk 14]
```diff
@@ -1,88 +1,356 @@
...
+import * as Helpers from 'atom-linter';
 
-const startMeasure = (baseName) => {
-  const startMark = `${baseName}-start`;
-  // Clear start mark from previous execution for the same file
-  if (performance.getEntriesByName(startMark).length) {
-    performance.clearMarks(startMark);
-  }
-  performance.mark(startMark);
+const configurationFile = '.codeclimate.yml';
```
Comment (Arcanemagus) [inline lib/index.js]: This should just be declared directly where it is being used, if later on this becomes something that needs configuring it can be changed then.

File: lib/index.js [hunk 15]
```diff
@@ -1,88 +1,356 @@
...
+const execArgs = ['analyze', '-f', 'json'];
+const logHeader = 'linter-codeclimate::';
+const linting = {};
+const fingerprints = {};
+const debounceTimeout = 250;
+const mapSeverity = {
```
Comment (Arcanemagus) [inline lib/index.js]: I would leave this down in the function where it is used.

**Review by Arcanemagus — CHANGES_REQUESTED** [review]
Here's some issues, both logic and design, that I see from a quick first pass.

**Comment by cgalvarez** [comment]
@Arcanemagus Thank you very much for detailed review. I'll take a look at all your reported issues ASAP and make a new commit to fix them all.

File: lib/index.js (hunk 1 above)
Comment (cgalvarez) [reply lib/index.js]: After making all functions that access to properties/methods of the package object, this can be removed.

File: lib/index.js (hunk 3 above)
Comment (cgalvarez) [reply lib/index.js]: You're right. I forgot to populate that prop to cache project root and textEditor.

File: lib/index.js (hunk 5 above)
Comment (cgalvarez) [reply lib/index.js]: Totally agree. My fault!

File: lib/index.js (hunk 10 above)
Comment (cgalvarez) [reply lib/index.js]: If I remove the debounce, everytime I save a file `Helpers.exec()` runs twice, and the more consecutive calls the more time spent in the Code Climate analysis.

For example, consecutive savings of a `lib/index.js` without changes for this project...

- ...once triggers a new analysis with 2 `Helpers.exec()` calls, and it last ~30s.
- ...twice triggers a new analysis with 4 `Helpers.exec()` calls, and it last ~48s.
- ...thrice triggers a new analysis with 6 `Helpers.exec()` calls, and it last ~62s.

The more consecutive savings, the more analysis lasts. You can check that with a task manager... lots of Docker threads are spawned.

Maybe you refer to the `uniqueKey` feature that should handle the spawned clis and kill previously called ones? I've already reported in `sb-exec` repo that it is not working as intended. Currently it doesn't kill the processes with the same key as soon as they are requested. Simply keeps executing them all and after finishing takes the last one.

If not, then that debounce call seems to be broken.

With my debounce approach you always get 1 `Helpers.exec()` call for consecutive savings (while below 250ms between keystrokes), and always get a duration of ~24s. If time between keystrokes is greater than 250ms, then the same issue from `sb-exec` appears.

**Comment by cgalvarez** [comment]
I've just fixed all your reported issues. Let me know If I've missed something or you want me to make a rebase or something :wink: 

I think it would be desirable to disable some Code Climate engines run in CI to make tests run faster.

File: lib/index.js (hunk 5 above)
Comment (Arcanemagus) [reply lib/index.js]: I made the same mistake when first implementing `uniqueKey` usage, that's how I know it's an issue 😆.

File: lib/index.js (hunk 10 above)
Comment (Arcanemagus) [reply lib/index.js]: Very interesting, good to know!

File: lib/index.js [hunk 16]
```diff
@@ -120,163 +220,205 @@ export default {
...
+  /**
+   * @summary Cache and keeps track of open textEditors and cache its file/project paths.
+   * @param   {TextEditor} textEditor TextEditor instance of the file which triggered the analysis.
+   */
+  async cacheEditor(textEditor) {
+    const path = textEditor.getPath();
+
+    if (this.cache[path]) return;
+
+    textEditor.onDidDestroy(() => delete this.cache[path]);
```
Comment (Arcanemagus) [inline lib/index.js:299]: Nice solution to keeping the cache but invalidating it when needed. The only potential issue is that you need to remember to re-populate it if the `TextEditor`'s path is missing from the cache (which you did where needed 👍).

**Review by Arcanemagus — APPROVED** [review]
Great work, thanks a ton for taking this on!

**Comment by Arcanemagus** [comment]
Since CI is passing, and I can't run this locally (Windows), I'll go ahead and merge this. 😆

**Comment by Arcanemagus** [comment]
@cgalvarez Assuming @AtomLinter/linter-codeclimate has no issues with it, if you want to be brought on as a maintainer for this project I would be fine with that 😉.

**Comment by Arcanemagus** [comment]
Published in v0.3.0 🎉.

**Comment by cgalvarez** [comment]
@Arcanemagus Great! I will be glad to help anytime I can.
